application: xz-airy-aria-8
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: media

- url: /.*
  script: tryexpo.app

libraries:
- name: jinja2
  version: latest